#!/bin/sh
echo "PROJECT_ID: ${PROJECT_ID}"
echo "ORG_NAME: ${ORG_NAME}"
echo "ORG_DISPLAY_NAME: ${ORG_DISPLAY_NAME}"
echo "ORGANIZATION_DESCRIPTION: ${ORGANIZATION_DESCRIPTION}"
echo "ANALYTICS_REGION: ${ANALYTICS_REGION}"
echo "RUNTIMETYPE: ${RUNTIMETYPE}"
echo "MOUNT: ${MOUNT}"
echo "VERSION: ${VERSION}"
echo "HYBRIDFILES: ${HYBRIDFILES}"
echo "APIGEECTL_HOME: ${APIGEECTL_HOME}"
echo "CERTLOC: ${CERTLOC}"
echo "OVERRIDEFILE: ${OVERRIDEFILE}"

